### PR TITLE
Be safe on dependency versions and speed up the typical build process.

### PR DESCRIPTION
**Pull request by Traumflug**
Some of the changes are due to sorting the list of dependencies by their name.

Dependencies were changed to a fixed version. In an ideal world, newer versions never break something, but in reality they sometimes do. Another reason for fixed versions is developer collaboration: PrestaShop has quite a number of commits where versions are changed up and down due to distinct developers having different package versions installed.

The other commit makes CSS compilation significantly faster. Typically, one file is changed, only, so compiling all the other files is a waste of time.

### CODE REVIEW

**Comment by firstred** [comment]
Thank you. That is useful!

I think we can use tilde (`~`) to lock to patch versions, like we do with our composer packages. I know that in the JavaScript hipster world those patch versions are quickly abandoned, but that shouldn't matter for our project.

**Comment by Traumflug** [comment]
Added these '~' to both commits already.

**Comment by kpodemski** [comment]
Can you show me the difference before and after your change to the compilation function? Gulp watcher is working and modifying only those modified files, not sure if your change takes into account imported files etc.

**Comment by Traumflug** [comment]
> Can you show me the difference before and after your change to the compilation function?

https://github.com/thirtybees/community-theme-default/pull/1/commits/5933f395dac9a5eb57fc72eaf3e6cb15aae31a02

> Gulp watcher is working and modifying only those modified files

It always compiled all of them: https://github.com/thirtybees/community-theme-default/blob/master/gulpfile.js#L79

> not sure if your change takes into account imported files etc.

Unlike with PS 1.7, there are not imported files.

**Comment by kpodemski** [comment]
I think that you got something wrong here, do you edit .css files or .scss files? If .scss, look here:
https://github.com/thirtybees/community-theme-default/blob/master/sass/global.scss no imported files?

On both of my machines (pc, macbook pro) compilation time is around 200-400ms, of course first compilation is longer because gulp needs to index all .scss files to the watcher cache, but second compilation is fast.

Edit:

ok, now i got this, you want to change file without having watcher enabled, right? just run the build again, yes? If so, your change does makes sense :)

**Comment by Traumflug** [comment]
I'll stop this Kindergarten right here.

**Comment by kpodemski** [comment]
Hm? Have you read my edit message?

**Pull request closed without merging**
