### PR TITLE
Sass files update 

### PR DESCRIPTION
**Pull request by Zengraph**
Few modifications on sass files and the css files are compiled without error log.

### CODE REVIEW

**Comment by firstred** [comment]
Thanks! But can you rebase it to only contain the last two commits? I see commits that shouldn't be in the PR.

**Comment by Zengraph** [comment]
Hello, I wish i can do that.. but i can't find where to delete or edit the commits in this PR.

Edit : I just closed it then.. I guess it's the best option

**Comment by firstred** [comment]
Ahh damn
Let me take care of it then!

**Comment by firstred** [comment]
Have you seen our blogpost about contributing BTW?
https://thirtybees.com/blog/contributing-to-thirty-bees-on-windows/

For the tutorial we used a program called GitKraken. I'm still learning it, but I think it is a very easy GUI to quickly learn git.

**Comment by firstred** [comment]
Ahh, now I see why. You worked on the 1.0.x branch, but the changes were meant for 1.1.x
Make sure you locally switch to 1.1.x

**Comment by firstred** [comment]
Okay, I got them on top of 1.1.x: https://github.com/thirtybees/community-theme-default/commits/1.1.x

Make sure you switch to 1.1.x (`git checkout 1.1.x`) then add this remote (`git remote add upstream https://github.com/thirtybees/community-theme-default`) and finally `git pull upstream 1.1.x`.

**Comment by Dh42** [comment]
I am on mobile and cant look at the whole request but i saw lato as the font. Should we think about going to noto in the 1.1.x branch?

**Comment by Zengraph** [comment]
firstred: I just started to test how things work here, I use Github desktop to commit on my fork. I am not sure 1.1 received my modified files.. I am searching a clean way.

Dh42: Why not for NOTO.. If you prefer that than lato, I'll do it in next commit.

**Comment by Dh42** [comment]
@Zengraph  My reasoning for noto might not be the best, but my thoughts are since it is a default theme it would be a good one since it has so many char sets. We could even play around with it and add charsets based on the shop language as well to give the shop good speed and still translate.

**Comment by Zengraph** [comment]
Good idea ! 

I am going to include nato to start playing with it on 1.1.x branch

**Comment by Zengraph** [comment]
NOTO..indeed

**Comment by Traumflug** [comment]
> Hello, I wish i can do that.. but i can't find where to delete or edit the commits in this PR.

One simply changes the pull-requested branch. Like rebasing it in your local copy, then `push -f` it to your fork on Github. That's it, the pull request recognizes this immediately.

**Comment by Traumflug** [comment]
> For the tutorial we used a program called GitKraken.

Key to success with Git for me was to kick away all these GUI tools. They just add complexity and make understanding Git harder. With one exception: Gitk. As viewer, only.

**Comment by Zengraph** [comment]
I installed GIT Kraken... and it helps to send pull request, github desktop don't do it. But it's like making the pull request from github.com I can't choose wich commit I'd like to send.
About the console commands, i did not understand your sentence "One simply changes the pull-requested branch. Like rebasing it in your local copy, then push -f it to your fork on Github."
What do to exactly, on a windows10 platform ? Not a native english speaker so rebasing.. means what ?

**Comment by Traumflug** [comment]
> windows10 platform

Forget it. I didn't say anything.

**Comment by Zengraph** [comment]
yes you did, so imagine you were on mac osx or linux or any OS you like better... 
from there what do you mean by "rebasing" and changes the pull-requested branch.

**Comment by Traumflug** [comment]
Windows 10 has a command line, so that's not the problem. Part of the problem is that Git comes with a learning curve and all those GUI tools try to avoid this curve, so one can't, or isn't encouraged to learn Git with them. This reduces/degrades a Git repository to something like a backup tool, while TimeMachine whould be the better choice for doing backups.

Another problem is that I don't feel like giving a 30 hour seminar here. Rebasing is a very powerful technique, nonetheless totally out of fashion, so one can barely find tutorials for it. Just two months ago I had a long discussion on the Git(!) mailing list where people tried hard to convince me to read an entire book about solving complex conflicts instead of just doing a rebase.

Perhaps because rebasing is something Git can do, but many other VCS' (SVN, Bazaar) can not. People often come along like "With SVN I did it this way, how do I the same with Git?". There's also only a small tendency to take advantage of the repository history, like bisecting, so people don't miss much when they use Git like Time Machine.

If you still want to know what rebasing is, look up "working with topic branches". A pull request is such a topic branch.

Oh, and perhaps I'm entirely wrong myself, perhaps Git and Github _are_ a Time Machine :-)

**Comment by Zengraph** [comment]
Thank you for these explanations.. that totaly confuse me.. but hey, that is not gonna stop me and I'll finnaly understand it one day... for that I'll follow your advice and read about  : "working with topic branches"... I hope to find something translated in my own language to help me dive into.

**Pull request closed without merging**
