### PR TITLE
Last modifications

### PR DESCRIPTION
**Pull request by Zengraph**
Better responsiveness in header, and more mods.

### CODE REVIEW

**Comment by firstred** [comment]
Looks like this pr has become a mess. Are there any commits we should still try to recover and merge?

**Comment by Zengraph** [comment]
I believe we should start from an updated version in order to have clean pull requests to deal with, I am going to delete my repos and start again

**Comment by ghost** [comment]
I agree.  It may also be helpful to delete any older versions of downloads.

**Comment by firstred** [comment]
Did you ever find the chance to redo this PR?

**Pull request closed without merging**
